apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  hostIPC: true
  securityContext:
    runAsUser: 1000
  containers:
    - name: cuda-vector-add
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          cpu: 100m
          memory: 1G
          nvidia.com/gpu-5gb: 1

